### ISSUE TITLE
Interrupted YouTube upload handling

### ISSUE THREAD

**Issue by koppi** [tokland/shoogle#1]
Is there a way to continue an interrupted / failed upload to YouTube?

**Comment by tokland** [comment]
Not that I know of.

**Comment by tokland** [comment]
Since it's not an issue with the package, I'll close it. You can seek more info at StackOverflow or other sites (and hopefully return with an answer). Thanks.

**Comment by koppi** [comment]
The YouTube API has resumable uploads, see: 
 https://developers.google.com/youtube/2.0/developers_guide_protocol_resumable_uploads#Sending_a_Resumable_Upload_API_Request

It would be cool to have support for this.

**Comment by tokland** [comment]
@koppi: shoogle uses the python api, not direct HTTP requests. So we need either a way of doing it with python or someone willing to invest the time of adding all this infrastructure to the package.

**Comment by koppi** [comment]
ok
