### ISSUE TITLE
How to authenticate with API Key (not oauth2)?

### ISSUE THREAD

**Issue by tcarreira** [tokland/shoogle#14]
Is it possible to authenticate with Google API Key, instead of OAuth token?

Google's documentation only states "include parameter key=API_KEY", but I can't find out what that means with shoogle. 
Would you help me? Is this possible?

**Comment by tokland** [comment]
I am sorry, but I am not using the Google services nor this package anymore, not sure if you can use an API key with the python library.

**Comment by tcarreira** [comment]
I could not find any way to do it, but it would be nice.
I had to do it using the OAuth authentication method anyway.

Thank you for your answer
