### ISSUE TITLE
How to list uploaded videos?

### ISSUE THREAD

**Issue by DavidVentura** [tokland/shoogle#2]
The youtube-samples account has some broken examples and I don't get how to list all the videos I've uploaded (unlisted) to my account.

Edit:

For now I've got:

`echo '{ "part": "snippet", "mine":true}' | shoogle execute youtube:v3.playlists.list -c client_secrets.json -`

but I get this response (The channel exists and has over 100 videos)

```
[ERROR] Server error response (404): {
 "error": {
  "errors": [
   {
    "domain": "youtube.playlist",
    "reason": "channelNotFound",
    "message": "Channel not found.",
    "locationType": "parameter",
    "location": "channelId"
   }
  ],
  "code": 404,
  "message": "Channel not found."
 }
}

```

**Comment by tokland** [comment]
See the first note in the feedback section.
