### ISSUE TITLE
Problem with the cached credentials

### ISSUE THREAD

**Issue by Konstantinusz** [tokland/shoogle#6]
I have three youtube account, and when I try to use the Shoogle utility for them, there is no problem for the first account. But after that when I try to use it for the next account, I always get a 403 error (forbidden).

Of course I attach the appropriate .json file with option -c containing the credentials saved from the developer console.

If I delete the cached credentials from .shoogle/credentials/default directory then everything is working again, after I paste the access code (which looks like "4/...."), but only for the newly authorized account. When I try again a different one, then I get a 403 error again.

So it looks like the utility picks up a wrong cached credential file from the .shoogle/credentials/default directory.

**Comment by tokland** [comment]
Did you try the credentials profile option of `execute`?
```
 --credentials-profile NAME
   Select credentials profile to use
```

**Comment by tokland** [comment]
Stalled
