### ISSUE TITLE
Allow --media-file from url

### ISSUE THREAD

**Issue by patcon** [tokland/shoogle#7]
This is great! Thanks for making this!

Not super-urgent, as it's easy to curl first, but seems like it might be nice to be able to upload to youtube from a remote url :)

**Comment by tokland** [comment]
AFAIK, there is no option to use a remote url, only a local file. Did you find something in the API?

**Comment by patcon** [comment]
No no sorry, there is just [another cli tool](https://github.com/porjo/youtubeuploader) that helpfully allows this, so I thought I'd make the ask. If you feel it's out of scope, I totally understand :)

**Comment by tokland** [comment]
I was curious how the scripts does it:

> When specifying a URL as the filename, the data will be streamed through the localhost (download from remote host, then upload to Youtube)

I prefer a shoogle user to download the files, indeed :)
